version: '3'

services:
  api:
      image: ronasit/php-nginx-dev:8.0
      container_name: pinia-plugin-persistedstate-reproduce-api
      working_dir: /app
      ports:
          - 80:80
          - 443:443
      volumes:
          - ./:/app
      links:
        - pgsql
        - pgsql_test
      environment:
          WEB_DOCUMENT_ROOT: /app/public
          WEB_DOCUMENT_INDEX: index.php
          REDIS_PORT: "6379"
          XDEBUG_START_WITH_REQUEST: "yes"
          XDEBUG_CLIENT_PORT: 9000
          XDEBUG_CLIENT_HOST: host.docker.internal
      networks:
        - pinia-plugin-persistedstate-reproduce

  pgsql:
    image: postgres:15rc2
    container_name: pinia-plugin-persistedstate-reproduce-pgsql
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: "pgpassword"
      POSTGRES_USER: pguser
      POSTGRES_DB: pgdb
    volumes:
      - .:/app
    networks:
      - pinia-plugin-persistedstate-reproduce

  pgsql_test:
    image: postgres:15rc2
    container_name: pinia-plugin-persistedstate-reproduce-pgsql-test
    ports:
        - 5434:5432
    environment:
      POSTGRES_PASSWORD: "pgpassword"
      POSTGRES_USER: pguser
      POSTGRES_DB: pgdb
    volumes:
    - .:/app
    command: ["-c", "fsync=off"]
    networks:
      - pinia-plugin-persistedstate-reproduce

  redis:
    image: redis:4
    container_name: pinia-plugin-persistedstate-reproduce-redis
    ports:
      - 6379:6379
    networks:
      - pinia-plugin-persistedstate-reproduce

networks:
  pinia-plugin-persistedstate-reproduce:
    external: true
